name: Terraform Apply (Manual)

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false

      # 🔧 STEP مؤقت – استيراد Helm Release الموجود بالفعل
      - name: Import ALB Controller Helm Release (one-time)
        run: |
          terraform import \
            module.k8s_addons.helm_release.alb_controller \
            kube-system/aws-load-balancer-controller || true

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name netflix-eks-cluster

      - name: Terraform Apply
        env:
          TF_VAR_jenkins_user_public_key: ${{ secrets.JENKINS_USER_PUBLIC_KEY }}
          TF_VAR_jenkins_nodes_public_key: ${{ secrets.JENKINS_NODES_PUBLIC_KEY }}
          TF_VAR_jenkins_nodes_private_key: ${{ secrets.JENKINS_NODES_PRIVATE_KEY }}
        run: terraform apply -auto-approve

      - name: Show Terraform Outputs
        run: terraform output
