name: Terraform Targeted Apply (Manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type APPLY to confirm targeted deployment"
        required: true

jobs:
  targeted-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Confirm execution
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "APPLY" ]; then
            echo "Confirmation failed. Type APPLY to confirm targeted apply."
            exit 1
          fi

      - name: Terraform Targeted Apply
        env:
          TF_VAR_jenkins_user_public_key: ${{ secrets.JENKINS_USER_PUBLIC_KEY }}
          TF_VAR_jenkins_nodes_public_key: ${{ secrets.JENKINS_NODES_PUBLIC_KEY }}
          TF_VAR_jenkins_nodes_private_key: ${{ secrets.JENKINS_NODES_PRIVATE_KEY }}
        run: |
          terraform apply -auto-approve \
            -target=module.vpc \
            -target=module.subnets \
            -target=module.security_groups \
            -target=module.eks \
            -target=module.iam \
            -target=module.iam_irsa \
            -target=module.k8s_addons.helm_release.alb_controller \
            -target=module.k8s_addons.helm_release.external_secrets \
            -target=module.k8s_addons.helm_release.reloader
